const http = require('http');
const socketIo = require('socket.io');
const app = require('./app');
const botService = require('./bot');
const database = require('./database');

const server = http.createServer(app);

// Socket.io integration (allow Next.js frontend port 3000)
const io = socketIo(server, {
  cors: {
    origin: 'http://localhost:3000',
    credentials: true,
    methods: ['GET', 'POST']
  }
});

// Give botService reference to IO
botService.setIo(io);

// Socket connection listener
io.on('connection', (socket) => {
  console.log('[Socket] Client connected:', socket.id);
  
  // Send initial data to client on connect
  socket.emit('status_update', {
    nextInformalCountdown: getNextInformalCountdown(),
    botReady: botService.isReady ? botService.isReady() : false
  });

  socket.on('disconnect', () => {
    console.log('[Socket] Client disconnected:', socket.id);
  });
});

// -------------------------------------------------------------
// EVENT SCHEDULERS & TIMER LOOPS
// -------------------------------------------------------------
const INFORMAL_INTERVAL_MS = 104 * 60 * 1000; // 1 hour 44 minutes = 104 minutes
let nextInformalTime = Date.now() + INFORMAL_INTERVAL_MS;

function getNextInformalCountdown() {
  const diff = nextInformalTime - Date.now();
  return diff > 0 ? Math.max(0, diff) : 0;
}

// Scheduled interval for Informal Signup reminder
setInterval(async () => {
  nextInformalTime = Date.now() + INFORMAL_INTERVAL_MS;
  
  // Embed details
  const embed = {
    title: '⚔️ INFORMAL GUNFIGHT REMINDER',
    description: 'An Informal family gunfight is starting in **10 minutes**! Prepare weapons, armor plates, and join the tactical radio frequency.',
    color: 0xff007f // Neon Magenta/Pink
  };

  // Dispatch notifications
  await botService.sendWebhook('informal-signup', embed);
  
  // Push live banner notification to all connected website clients
  io.emit('system_notification', {
    title: 'Informal Reminder',
    message: 'An Informal gunfight is starting in 10 minutes! Join the fight!',
    type: 'warning',
    duration: 15000 // 15 seconds visibility
  });

  io.emit('status_update', {
    nextInformalCountdown: INFORMAL_INTERVAL_MS
  });
  
  botService.logSimulated('Automated reminder fired for hourly Informal Gunfight.');
}, INFORMAL_INTERVAL_MS);

// Helper socket sync broadcast (runs every 10 seconds to sync timers)
setInterval(() => {
  io.emit('timer_sync', {
    nextInformalCountdown: getNextInformalCountdown()
  });
}, 10000);

// Minute-by-minute automated signup scheduler loop for RP Ticket signups
let lastTriggeredTime = '';
setInterval(async () => {
  try {
    const now = new Date();
    const hh = String(now.getHours()).padStart(2, '0');
    const mm = String(now.getMinutes()).padStart(2, '0');
    const currentTime = `${hh}:${mm}`;

    if (currentTime === lastTriggeredTime) return;

    const config = await database.getConfig();
    const rpTicketTimes = config.rpTicketTimes || ["08:30", "15:00", "20:00", "22:30"];

    if (rpTicketTimes.includes(currentTime)) {
      lastTriggeredTime = currentTime;
      console.log(`[Scheduler] Automatically opening RP Ticket signup at scheduled time: ${currentTime}`);
      
      // Clear previous signups and open registration
      await database.clearSignups('rp-signup');
      await database.setEventState('rp-signup', 'open');
      
      // Emit socket updates to web clients
      io.emit('event_state_change', { eventId: 'rp-signup', state: 'open' });
      io.emit('signup_change', { eventId: 'rp-signup', signups: [] });
      
      // Trigger the Discord bot message (sends double buttons: Signup and Leave)
      await botService.triggerEventSignup(
        'rp-signup',
        'RP Ticket - Autogenerated',
        'Automated RP Ticket signup window. Sign up now! Roster limit: 25. Top 10 members can displace non-Top 10 players.',
        15
      );
      
      io.emit('system_notification', {
        title: 'Roster Opened',
        message: 'The automated RP Ticket signup roster has been opened!',
        type: 'success'
      });
      
      botService.logSimulated(`Automated scheduler fired RP Ticket signup at ${currentTime}`);
    }
  } catch (err) {
    console.error('[Scheduler] Error in check loop:', err);
  }
}, 30000);

// -------------------------------------------------------------
// BOOTSTRAP
// -------------------------------------------------------------
const PORT = process.env.PORT || 5000;

server.listen(PORT, async () => {
  console.log(`[Server] Express listening on http://localhost:${PORT}`);
  
  // Try connecting bot
  try {
    await botService.init();
  } catch (err) {
    console.error('[Server] Bot initialization failed:', err.message);
  }
});
